// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "cmedpanel.H"
#include "cmed.H"

Fl_Button *undobutton=(Fl_Button *)0;

Fl_Slider *forceslider=(Fl_Slider *)0;

Fl_Button *rgbmode=(Fl_Button *)0;

Fl_Input *fnamebox=(Fl_Input *)0;

class CMedit *cmedit=(class CMedit *)0;

Fl_Menu_Item menu_[] = {
 {"&File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Save Color File... ", 0x40073,  (Fl_Callback*)menu_fsave_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Load Color File...", 0x4006c,  (Fl_Callback*)menu_fload_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"load histogram file...", 0x5006c,  (Fl_Callback*)menu_histfload_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"&Edit", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Undo", 0x4007a,  (Fl_Callback*)menu_undo_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Value_Input *cmap_min=(Fl_Value_Input *)0;

Fl_Value_Input *cmap_max=(Fl_Value_Input *)0;

Fl_Value_Input *display_range_min=(Fl_Value_Input *)0;

Fl_Value_Input *display_range_max=(Fl_Value_Input *)0;

Fl_Output *hist_max=(Fl_Output *)0;

Fl_Output *hist_min=(Fl_Output *)0;

Fl_Slider *x_range_min_slider=(Fl_Slider *)0;

Fl_Slider *x_range_max_slider=(Fl_Slider *)0;

Fl_Value_Input *max_Y=(Fl_Value_Input *)0;

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(405, 605);
    w = o;
    { undobutton = new Fl_Button(6, 25, 40, 25, "Undo");
      undobutton->down_box(FL_DOWN_BOX);
      undobutton->callback((Fl_Callback*)undo_cb);
    } // Fl_Button* undobutton
    { forceslider = new Fl_Slider(206, 25, 75, 25, "Force");
      forceslider->type(5);
      forceslider->selection_color((Fl_Color)1);
      forceslider->minimum(0.05);
      forceslider->value(0.5);
      forceslider->callback((Fl_Callback*)lerp_cb);
      forceslider->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Slider* forceslider
    { rgbmode = new Fl_Button(331, 25, 35, 25, "HSB");
      rgbmode->labelsize(12);
      rgbmode->callback((Fl_Callback*)rgbmode_cb);
      rgbmode->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
    } // Fl_Button* rgbmode
    { fnamebox = new Fl_Input(31, 60, 355, 25, "File:");
      fnamebox->labeltype(FL_ENGRAVED_LABEL);
      fnamebox->labelsize(12);
      fnamebox->callback((Fl_Callback*)input_cb);
      fnamebox->when(FL_WHEN_ENTER_KEY_ALWAYS);
    } // Fl_Input* fnamebox
    { cshow.hsblbls[0] = new Fl_Box(30, 219, 80, 20, "Hue (L)");
      cshow.hsblbls[0]->box(FL_FLAT_BOX);
      cshow.hsblbls[0]->color((Fl_Color)34);
      cshow.hsblbls[0]->labelfont(1);
      cshow.hsblbls[0]->labelsize(12);
      cshow.hsblbls[0]->labelcolor((Fl_Color)3);
    } // Fl_Box* cshow.hsblbls[0]
    { cshow.hsblbls[1] = new Fl_Box(115, 219, 75, 20, "Sat(M)");
      cshow.hsblbls[1]->box(FL_FLAT_BOX);
      cshow.hsblbls[1]->color((Fl_Color)34);
      cshow.hsblbls[1]->labelfont(1);
      cshow.hsblbls[1]->labelsize(12);
      cshow.hsblbls[1]->labelcolor((Fl_Color)2);
    } // Fl_Box* cshow.hsblbls[1]
    { cshow.hsblbls[2] = new Fl_Box(195, 219, 75, 20, "Bright(R)");
      cshow.hsblbls[2]->box(FL_FLAT_BOX);
      cshow.hsblbls[2]->color((Fl_Color)34);
      cshow.hsblbls[2]->labelfont(1);
      cshow.hsblbls[2]->labelsize(12);
      cshow.hsblbls[2]->labelcolor((Fl_Color)235);
    } // Fl_Box* cshow.hsblbls[2]
    { Fl_Box* o = new Fl_Box(275, 219, 80, 20, "Alpha(shift)");
      o->box(FL_FLAT_BOX);
      o->color((Fl_Color)34);
      o->labelfont(1);
      o->labelsize(12);
      o->labelcolor(FL_BACKGROUND2_COLOR);
    } // Fl_Box* o
    { cmedit = new class CMedit(5, 239, 380, 270);
      cmedit->box(FL_FLAT_BOX);
      cmedit->color(FL_BACKGROUND_COLOR);
      cmedit->selection_color(FL_BACKGROUND_COLOR);
      cmedit->labeltype(FL_NORMAL_LABEL);
      cmedit->labelfont(0);
      cmedit->labelsize(14);
      cmedit->labelcolor(FL_FOREGROUND_COLOR);
      cmedit->align(Fl_Align(FL_ALIGN_CENTER));
      cmedit->when(FL_WHEN_RELEASE);
      Fl_Group::current()->resizable(cmedit);
    } // class CMedit* cmedit
    { cshow.color = new colorpatch(62, 515, 50, 40);
      cshow.color->box(FL_DOWN_BOX);
      cshow.color->color(FL_BACKGROUND_COLOR);
      cshow.color->selection_color(FL_BACKGROUND_COLOR);
      cshow.color->labeltype(FL_NO_LABEL);
      cshow.color->labelfont(0);
      cshow.color->labelsize(14);
      cshow.color->labelcolor(FL_FOREGROUND_COLOR);
      cshow.color->align(Fl_Align(FL_ALIGN_CENTER));
      cshow.color->when(FL_WHEN_RELEASE);
    } // colorpatch* cshow.color
    { cshow.cindex = new Fl_Value_Input(7, 530, 50, 25, "  (index");
      cshow.cindex->box(FL_FLAT_BOX);
      cshow.cindex->color((Fl_Color)16);
      cshow.cindex->maximum(0);
      cshow.cindex->step(1);
      cshow.cindex->textsize(12);
      cshow.cindex->callback((Fl_Callback*)report_cb);
      cshow.cindex->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Value_Input* cshow.cindex
    { cshow.hsba = new Fl_Output(117, 530, 120, 25, "HSBA");
      cshow.hsba->box(FL_FLAT_BOX);
      cshow.hsba->color((Fl_Color)16);
      cshow.hsba->textsize(11);
      cshow.hsba->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Output* cshow.hsba
    { cshow.rgba = new Fl_Output(247, 530, 125, 25, "rgb");
      cshow.rgba->box(FL_FLAT_BOX);
      cshow.rgba->color((Fl_Color)16);
      cshow.rgba->textsize(11);
      cshow.rgba->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Output* cshow.rgba
    { cshow.postscalein = new Fl_Value_Input(317, 570, 65, 25, "* Amax");
      cshow.postscalein->callback((Fl_Callback*)ascale_cb);
      cshow.postscalein->align(Fl_Align(FL_ALIGN_TOP_LEFT));
    } // Fl_Value_Input* cshow.postscalein
    { cshow.postexponin = new Fl_Value_Input(237, 570, 75, 25, "**  expon  )");
      cshow.postexponin->callback((Fl_Callback*)ascale_cb);
      cshow.postexponin->align(Fl_Align(FL_ALIGN_TOP_LEFT));
    } // Fl_Value_Input* cshow.postexponin
    { cshow.cmentin = new Fl_Value_Input(7, 570, 55, 25, "cmapsize");
      cshow.cmentin->box(FL_ENGRAVED_BOX);
      cshow.cmentin->color((Fl_Color)25);
      cshow.cmentin->callback((Fl_Callback*)ncment_cb);
      cshow.cmentin->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      cshow.cmentin->when(FL_WHEN_RELEASE);
    } // Fl_Value_Input* cshow.cmentin
    { cshow.scaleout = new Fl_Output(137, 570, 95, 25, "  Aout  =  ( Ain");
      cshow.scaleout->box(FL_FLAT_BOX);
      cshow.scaleout->color((Fl_Color)16);
      cshow.scaleout->align(Fl_Align(FL_ALIGN_TOP_LEFT));
    } // Fl_Output* cshow.scaleout
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 405, 20);
      o->color((Fl_Color)46);
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    { Fl_Group* o = new Fl_Group(5, 86, 400, 154);
      { Fl_Group* o = new Fl_Group(10, 86, 380, 118);
        { cmap_min = new Fl_Value_Input(151, 124, 89, 25, "Cmap Range:   Min");
          cmap_min->callback((Fl_Callback*)cmap_range_min);
          cmap_min->when(FL_WHEN_RELEASE);
        } // Fl_Value_Input* cmap_min
        { cmap_max = new Fl_Value_Input(290, 124, 95, 25, "Max");
          cmap_max->value(1);
          cmap_max->callback((Fl_Callback*)cmap_range_max);
          cmap_max->when(FL_WHEN_RELEASE);
        } // Fl_Value_Input* cmap_max
        { display_range_min = new Fl_Value_Input(151, 154, 89, 25, "Display Range: Min");
          display_range_min->callback((Fl_Callback*)display_data_range_min);
          display_range_min->when(FL_WHEN_RELEASE);
        } // Fl_Value_Input* display_range_min
        { display_range_max = new Fl_Value_Input(290, 154, 95, 25, "Max");
          display_range_max->value(1);
          display_range_max->callback((Fl_Callback*)display_data_range_max);
          display_range_max->when(FL_WHEN_RELEASE);
        } // Fl_Value_Input* display_range_max
        { hist_max = new Fl_Output(290, 95, 95, 25, "Max");
          hist_max->color((Fl_Color)31);
        } // Fl_Output* hist_max
        { hist_min = new Fl_Output(151, 95, 89, 25, "Hist Range:    Min");
          hist_min->color((Fl_Color)31);
          hist_min->selection_color(FL_BACKGROUND2_COLOR);
        } // Fl_Output* hist_min
        { x_range_min_slider = new Fl_Slider(125, 181, 115, 19);
          x_range_min_slider->type(5);
          x_range_min_slider->callback((Fl_Callback*)x_range_min_cb);
          x_range_min_slider->align(Fl_Align(FL_ALIGN_LEFT));
        } // Fl_Slider* x_range_min_slider
        { x_range_max_slider = new Fl_Slider(265, 182, 120, 18);
          x_range_max_slider->type(5);
          x_range_max_slider->callback((Fl_Callback*)x_range_max_cb);
        } // Fl_Slider* x_range_max_slider
        o->end();
      } // Fl_Group* o
      { Fl_Box* o = new Fl_Box(390, 98, 5, 84);
        Fl_Group::current()->resizable(o);
      } // Fl_Box* o
      o->end();
    } // Fl_Group* o
    { max_Y = new Fl_Value_Input(360, 218, 40, 21, "Max Y: ");
      max_Y->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Value_Input* max_Y
    o->end();
  } // Fl_Double_Window* o
  return w;
}
