// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "cmedpanel.H"
#include "cmed.H"

Fl_Button *undobutton=(Fl_Button *)0;

Fl_Slider *forceslider=(Fl_Slider *)0;

Fl_Button *rgbmode=(Fl_Button *)0;

class CMedit *cmedit=(class CMedit *)0;

Fl_Menu_Item menu_[] = {
 {"&File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Save Color File... ", 0x40073,  (Fl_Callback*)menu_fsave_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Load Color File...", 0x4006c,  (Fl_Callback*)menu_fload_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"load histogram file...", 0x5006c,  (Fl_Callback*)menu_histfload_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"&Edit", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Undo", 0x4007a,  (Fl_Callback*)menu_undo_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Redo", 0x40079,  (Fl_Callback*)menu_redo_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"&Zoom", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Zoom Panel", 0,  (Fl_Callback*)zoom_panel_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"&Modes", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Drawing Mode", 0,  (Fl_Callback*)change_mode, (void*)(1), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Scaling Mode", 0,  (Fl_Callback*)change_mode, (void*)(2), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(400, 610);
    w = o;
    { undobutton = new Fl_Button(6, 25, 40, 25, "Undo");
      undobutton->down_box(FL_DOWN_BOX);
      undobutton->callback((Fl_Callback*)undo_cb);
    } // Fl_Button* undobutton
    { forceslider = new Fl_Slider(206, 25, 75, 25, "Force");
      forceslider->type(5);
      forceslider->selection_color((Fl_Color)1);
      forceslider->minimum(0.05);
      forceslider->value(0.5);
      forceslider->callback((Fl_Callback*)lerp_cb);
      forceslider->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Slider* forceslider
    { rgbmode = new Fl_Button(331, 25, 35, 25, "HSB");
      rgbmode->labelsize(12);
      rgbmode->callback((Fl_Callback*)rgbmode_cb);
      rgbmode->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
    } // Fl_Button* rgbmode
    { cshow.hsblbls[0] = new Fl_Box(40, 219, 80, 20, "Hue (L)");
      cshow.hsblbls[0]->box(FL_FLAT_BOX);
      cshow.hsblbls[0]->color((Fl_Color)34);
      cshow.hsblbls[0]->labelfont(1);
      cshow.hsblbls[0]->labelsize(12);
      cshow.hsblbls[0]->labelcolor((Fl_Color)3);
    } // Fl_Box* cshow.hsblbls[0]
    { cshow.hsblbls[1] = new Fl_Box(125, 219, 75, 20, "Sat(M)");
      cshow.hsblbls[1]->box(FL_FLAT_BOX);
      cshow.hsblbls[1]->color((Fl_Color)34);
      cshow.hsblbls[1]->labelfont(1);
      cshow.hsblbls[1]->labelsize(12);
      cshow.hsblbls[1]->labelcolor((Fl_Color)2);
    } // Fl_Box* cshow.hsblbls[1]
    { cshow.hsblbls[2] = new Fl_Box(205, 219, 75, 20, "Bright(R)");
      cshow.hsblbls[2]->box(FL_FLAT_BOX);
      cshow.hsblbls[2]->color((Fl_Color)34);
      cshow.hsblbls[2]->labelfont(1);
      cshow.hsblbls[2]->labelsize(12);
      cshow.hsblbls[2]->labelcolor((Fl_Color)235);
    } // Fl_Box* cshow.hsblbls[2]
    { Fl_Box* o = new Fl_Box(285, 219, 80, 20, "Alpha(shift)");
      o->box(FL_FLAT_BOX);
      o->color((Fl_Color)34);
      o->labelfont(1);
      o->labelsize(12);
      o->labelcolor(FL_BACKGROUND2_COLOR);
    } // Fl_Box* o
    { cmedit = new class CMedit(5, 239, 380, 270);
      cmedit->box(FL_FLAT_BOX);
      cmedit->color(FL_BACKGROUND_COLOR);
      cmedit->selection_color(FL_BACKGROUND_COLOR);
      cmedit->labeltype(FL_NORMAL_LABEL);
      cmedit->labelfont(0);
      cmedit->labelsize(14);
      cmedit->labelcolor(FL_FOREGROUND_COLOR);
      cmedit->align(Fl_Align(FL_ALIGN_CENTER));
      cmedit->when(FL_WHEN_RELEASE);
      Fl_Group::current()->resizable(cmedit);
    } // class CMedit* cmedit
    { cshow.color = new colorpatch(72, 515, 50, 40);
      cshow.color->box(FL_DOWN_BOX);
      cshow.color->color(FL_BACKGROUND_COLOR);
      cshow.color->selection_color(FL_BACKGROUND_COLOR);
      cshow.color->labeltype(FL_NO_LABEL);
      cshow.color->labelfont(0);
      cshow.color->labelsize(14);
      cshow.color->labelcolor(FL_FOREGROUND_COLOR);
      cshow.color->align(Fl_Align(FL_ALIGN_CENTER));
      cshow.color->when(FL_WHEN_RELEASE);
    } // colorpatch* cshow.color
    { cshow.cindex = new Fl_Value_Input(17, 530, 50, 25, "  (index");
      cshow.cindex->box(FL_FLAT_BOX);
      cshow.cindex->color((Fl_Color)16);
      cshow.cindex->maximum(0);
      cshow.cindex->step(1);
      cshow.cindex->textsize(12);
      cshow.cindex->callback((Fl_Callback*)report_cb);
      cshow.cindex->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Value_Input* cshow.cindex
    { cshow.hsba = new Fl_Output(127, 530, 120, 25, "HSBA");
      cshow.hsba->box(FL_FLAT_BOX);
      cshow.hsba->color((Fl_Color)16);
      cshow.hsba->textsize(11);
      cshow.hsba->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Output* cshow.hsba
    { cshow.rgba = new Fl_Output(257, 530, 125, 25, "rgb");
      cshow.rgba->box(FL_FLAT_BOX);
      cshow.rgba->color((Fl_Color)16);
      cshow.rgba->textsize(11);
      cshow.rgba->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Output* cshow.rgba
    { cshow.cmentin = new Fl_Value_Input(17, 570, 55, 25, "cmapsize");
      cshow.cmentin->box(FL_ENGRAVED_BOX);
      cshow.cmentin->color((Fl_Color)25);
      cshow.cmentin->callback((Fl_Callback*)ncment_cb);
      cshow.cmentin->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      cshow.cmentin->when(FL_WHEN_RELEASE);
    } // Fl_Value_Input* cshow.cmentin
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 400, 20);
      o->color((Fl_Color)46);
      { Fl_Menu_Item* o = &menu_[13];
        o->shortcut(FL_SHIFT + FL_ALT + 'd');
      }
      { Fl_Menu_Item* o = &menu_[14];
        o->shortcut(FL_SHIFT + FL_ALT + 's');
      }
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    { Fl_Button* o = new Fl_Button(55, 25, 70, 25, "Reset");
      o->callback((Fl_Callback*)display_reset_cb);
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_Double_Window *zoom_panel_window=(Fl_Double_Window *)0;

Fl_Value_Input *x_cmap_range_min_box=(Fl_Value_Input *)0;

Fl_Value_Input *x_cmap_range_max_box=(Fl_Value_Input *)0;

Fl_Value_Input *x_display_range_min_box=(Fl_Value_Input *)0;

Fl_Value_Input *x_display_range_max_box=(Fl_Value_Input *)0;

Fl_Output *x_hist_range_max_box=(Fl_Output *)0;

Fl_Output *x_hist_range_min_box=(Fl_Output *)0;

Fl_Slider *x_display_range_min_slider=(Fl_Slider *)0;

Fl_Slider *x_display_range_max_slider=(Fl_Slider *)0;

Fl_Output *y_hist_range_max_box=(Fl_Output *)0;

Fl_Output *y_hist_range_min_box=(Fl_Output *)0;

Fl_Value_Input *y_cmap_range_max_box=(Fl_Value_Input *)0;

Fl_Value_Input *y_cmap_range_min_box=(Fl_Value_Input *)0;

Fl_Value_Input *y_display_range_max_box=(Fl_Value_Input *)0;

Fl_Value_Input *y_display_range_min_box=(Fl_Value_Input *)0;

Fl_Slider *y_cmap_range_max_slider=(Fl_Slider *)0;

Fl_Slider *y_display_range_min_slider=(Fl_Slider *)0;

Fl_Slider *y_cmap_range_min_slider=(Fl_Slider *)0;

Fl_Slider *y_display_range_max_slider=(Fl_Slider *)0;

Fl_Double_Window* make_zoom_panel() {
  { zoom_panel_window = new Fl_Double_Window(670, 490, "Zoom Panel Window");
    { Fl_Group* o = new Fl_Group(0, 6, 417, 148);
      o->box(FL_UP_BOX);
      o->color((Fl_Color)92);
      { Fl_Group* o = new Fl_Group(22, 6, 380, 118);
        { x_cmap_range_min_box = new Fl_Value_Input(163, 44, 89, 25, "Cmap Range(X):   Min");
          x_cmap_range_min_box->callback((Fl_Callback*)x_cmap_range_min_box_cb);
          x_cmap_range_min_box->when(FL_WHEN_RELEASE);
        } // Fl_Value_Input* x_cmap_range_min_box
        { x_cmap_range_max_box = new Fl_Value_Input(302, 44, 95, 25, "Max");
          x_cmap_range_max_box->value(1);
          x_cmap_range_max_box->callback((Fl_Callback*)x_cmap_range_max_box_cb);
          x_cmap_range_max_box->when(FL_WHEN_RELEASE);
        } // Fl_Value_Input* x_cmap_range_max_box
        { x_display_range_min_box = new Fl_Value_Input(163, 74, 89, 25, "Display Range(X): Min");
          x_display_range_min_box->callback((Fl_Callback*)x_display_range_min_box_cb);
          x_display_range_min_box->when(FL_WHEN_RELEASE);
        } // Fl_Value_Input* x_display_range_min_box
        { x_display_range_max_box = new Fl_Value_Input(302, 74, 95, 25, "Max");
          x_display_range_max_box->value(1);
          x_display_range_max_box->callback((Fl_Callback*)x_display_range_max_box_cb);
          x_display_range_max_box->when(FL_WHEN_RELEASE);
        } // Fl_Value_Input* x_display_range_max_box
        { x_hist_range_max_box = new Fl_Output(302, 15, 95, 25, "Max");
          x_hist_range_max_box->color((Fl_Color)31);
        } // Fl_Output* x_hist_range_max_box
        { x_hist_range_min_box = new Fl_Output(163, 15, 89, 25, "Hist Range(X):    Min");
          x_hist_range_min_box->color((Fl_Color)31);
          x_hist_range_min_box->selection_color(FL_BACKGROUND2_COLOR);
        } // Fl_Output* x_hist_range_min_box
        { x_display_range_min_slider = new Fl_Slider(137, 101, 115, 19);
          x_display_range_min_slider->type(5);
          x_display_range_min_slider->callback((Fl_Callback*)x_display_range_min_slider_cb);
          x_display_range_min_slider->align(Fl_Align(FL_ALIGN_LEFT));
        } // Fl_Slider* x_display_range_min_slider
        { Fl_Slider* o = x_display_range_max_slider = new Fl_Slider(277, 102, 120, 18);
          x_display_range_max_slider->type(5);
          x_display_range_max_slider->callback((Fl_Callback*)x_display_range_max_slider_cb);
          o->value(o->maximum());
        } // Fl_Slider* x_display_range_max_slider
        o->end();
      } // Fl_Group* o
      { Fl_Box* o = new Fl_Box(402, 18, 5, 84);
        Fl_Group::current()->resizable(o);
      } // Fl_Box* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(420, 5, 245, 455);
      o->box(FL_UP_BOX);
      o->color((Fl_Color)214);
      { y_hist_range_max_box = new Fl_Output(562, 12, 93, 25, "Hist Range(Y) Max:");
        y_hist_range_max_box->color(FL_DARK1);
        y_hist_range_max_box->callback((Fl_Callback*)y_hist_range_max_box_cf);
      } // Fl_Output* y_hist_range_max_box
      { y_hist_range_min_box = new Fl_Output(517, 421, 95, 25, "Min:");
        y_hist_range_min_box->color((Fl_Color)46);
        y_hist_range_min_box->callback((Fl_Callback*)y_hist_range_min_box_cf);
      } // Fl_Output* y_hist_range_min_box
      { y_cmap_range_max_box = new Fl_Value_Input(446, 88, 70, 20, "Cmap Range(Y) \nMax:");
        y_cmap_range_max_box->callback((Fl_Callback*)y_cmap_range_max_box_cb);
        y_cmap_range_max_box->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Value_Input* y_cmap_range_max_box
      { y_cmap_range_min_box = new Fl_Value_Input(446, 372, 70, 20, "Min:");
        y_cmap_range_min_box->callback((Fl_Callback*)y_cmap_range_min_box_cb);
        y_cmap_range_min_box->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Value_Input* y_cmap_range_min_box
      { y_display_range_max_box = new Fl_Value_Input(565, 88, 72, 19, "Display Range(Y)\nMax:");
        y_display_range_max_box->callback((Fl_Callback*)y_display_range_max_box_cb);
        y_display_range_max_box->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Value_Input* y_display_range_max_box
      { y_display_range_min_box = new Fl_Value_Input(565, 371, 72, 19, "Min:");
        y_display_range_min_box->callback((Fl_Callback*)y_display_range_min_box_cb);
        y_display_range_min_box->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Value_Input* y_display_range_min_box
      { y_cmap_range_max_slider = new Fl_Slider(470, 122, 20, 98);
        y_cmap_range_max_slider->type(4);
        y_cmap_range_max_slider->callback((Fl_Callback*)y_cmap_range_max_slider_cb);
      } // Fl_Slider* y_cmap_range_max_slider
      { Fl_Slider* o = y_display_range_min_slider = new Fl_Slider(590, 234, 20, 98);
        y_display_range_min_slider->type(4);
        y_display_range_min_slider->callback((Fl_Callback*)y_display_range_min_slider_cb);
        o->value(o->maximum());
      } // Fl_Slider* y_display_range_min_slider
      { Fl_Slider* o = y_cmap_range_min_slider = new Fl_Slider(470, 235, 20, 98);
        y_cmap_range_min_slider->type(4);
        y_cmap_range_min_slider->callback((Fl_Callback*)y_cmap_range_min_slider_cb);
        o->value(o->maximum());
      } // Fl_Slider* y_cmap_range_min_slider
      { y_display_range_max_slider = new Fl_Slider(590, 120, 20, 98);
        y_display_range_max_slider->type(4);
        y_display_range_max_slider->callback((Fl_Callback*)y_display_range_max_slider_cb);
      } // Fl_Slider* y_display_range_max_slider
      o->end();
    } // Fl_Group* o
    zoom_panel_window->end();
  } // Fl_Double_Window* zoom_panel_window
  return zoom_panel_window;
}
